name: regional_workflow
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - astroid=2.14.2=py39h06a4308_0
  - attrs=22.1.0=py39h06a4308_0
  - blas=1.0=mkl
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2023.01.10=h06a4308_0
  - cartopy=0.18.0=py39h0d9ca2b_1
  - certifi=2022.12.7=py39h06a4308_0
  - colorama=0.4.6=py39h06a4308_0
  - curl=7.84.0=h5eee18b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - dill=0.3.6=py39h06a4308_0
  - eccodes=2.27.0=h164a9dd_0
  - expat=2.4.9=h6a678d5_0
  - f90nml=1.4.3=pyhd8ed1ab_0
  - fftw=3.3.9=h27cfd23_1
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.11.0=h70c0345_0
  - geos=3.8.0=he6710b0_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf4=4.2.15=h9772cbc_4
  - hdf5=1.12.2=nompi_h2386368_100
  - icu=58.2=he6710b0_3
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - isort=5.9.3=pyhd3eb1b0_0
  - jasper=2.0.33=ha77e612_0
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - kiwisolver=1.4.2=py39h295c915_0
  - krb5=1.19.2=hac12032_0
  - lazy-object-proxy=1.6.0=py39h27cfd23_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.6=h9c3ff4c_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libcurl=7.84.0=h91b91d3_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h516909a_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglu=9.0.0=he1b5a44_1001
  - libllvm10=10.0.1=hbcb73fb_5
  - libnetcdf=4.8.1=nompi_h21705cb_104
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libsqlite=3.39.4=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=hecacb30_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzip=1.9.2=hc869a4a_1
  - libzlib=1.2.12=h166bdaf_3
  - llvm-openmp=14.0.4=he0ac6c6_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib=3.5.2=py39h06a4308_0
  - matplotlib-base=3.5.2=py39hf590b9c_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h5eee18b_3
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numpy=1.23.1=py39h6c91a56_0
  - numpy-base=1.23.1=py39ha15fc14_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pillow=9.2.0=py39hace64e9_1
  - pip=22.2.2=py39h06a4308_0
  - platformdirs=2.5.2=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - ply=3.11=py39h06a4308_0
  - proj=6.2.1=h05a3930_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py=1.11.0=pyhd3eb1b0_0
  - pygrib=2.1.4=py39hb9ab73c_5
  - pylint=2.16.2=py39h06a4308_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyproj=2.6.1.post1=py39hb3025e9_1
  - pyqt=5.9.2=py39h2531618_6
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pyshp=2.1.3=pyhd3eb1b0_0
  - pytest=7.1.2=py39h06a4308_0
  - python=3.9.12=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pyyaml=6.0=py39h7f8727e_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - scipy=1.9.1=py39h14f4228_0
  - setuptools=63.4.1=py39h06a4308_0
  - shapely=1.8.4=py39h81ba7c5_0
  - sip=4.19.13=py39h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39h06a4308_0
  - tomlkit=0.11.1=py39h06a4308_0
  - tornado=6.2=py39h5eee18b_0
  - typing-extensions=4.4.0=py39h06a4308_0
  - typing_extensions=4.4.0=py39h06a4308_0
  - tzdata=2022c=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py39h5eee18b_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - boto3==1.26.88
    - botocore==1.29.88
    - jmespath==1.0.1
    - s3transfer==0.6.0
    - urllib3==1.26.14
prefix: /groups/ESS/pcampbe8/anaconda3/envs/regional_workflow                                                                                                                                             
